### ISSUE TITLE
"integer division or modulo by zero" error in 158 line train.py

### ISSUE THREAD

**Issue by Lukysoon** [bshall/hubert#15]
> -- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap fn(i, *args)
  File "/workspace/hubert/train.py", line 158, in train n_epochs = STEPS // len(train_loader) + 1
ZeroDivisionError: integer division or modulo by zero

I'm running on runpod with pod "RunPod Pytorch 2.1"

What could be a problem?

**Comment by Lukasis150** [comment]
I see I did not have dev-* and train-* folders in my wav directory.

**Comment by Lukasis150** [comment]
I see I did not have dev-* and train-* folders in my wav directory. So it didn't fit the pattern.

**Comment by Lukysoon** [comment]
I see I did not have dev-* and train-* folders in my wav directory. So it didn't fit the pattern.

**Comment by pyfit** [comment]
@Lukysoon can you share how to use train.py and the options? The README is not very descriptive.
